spring:
  # REDIS数据库配置
  redis:
    # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
    host: 192.168.1.55
    # [必须修改] 端口号
    port: 6379
    # [可选] 数据库 DB
    database: 8
    # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
    password: tianquekeji
    # [可选] 超时时间
    timeout: 10000000
  # [可选] jdbc数据库配置, 项目使用sqlite作为数据库，一般不需要配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wvp?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

# [可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
  port: 18081
  # [可选] HTTPS配置， 默认不开启
  ssl:
    # [可选] 是否开启HTTPS访问
    enabled: false
    # [可选] 证书文件路径，放置在resource/目录下即可，修改xxx为文件名
    key-store: classpath:xxx.jks
    # [可选] 证书密码
    key-password: password
    # [可选] 证书类型， 默认为jks，根据实际修改
    key-store-type: JKS

# [根据业务需求配置]
userSettings:
  # [必选 ] zlm配置的录像路径
  record: /usr/local/ZLMediaKit/release/linux/Debug/www/record
  # [可选 ] 录像保存时长（单位： 天）每天晚12点自动对过期文件执行清理
  recordDay: 7
  # [可选 ] 录像下载合成临时文件保存时长， 不配置默认取值recordDay（单位： 天）每天晚12点自动对过期文件执行清理
  # recordTempDay: 7
  # [必选 ] ffmpeg路径
  ffmpeg: /usr/bin/ffmpeg
  # [必选 ] ffprobe路径， 一般安装ffmpeg就会自带， 一般跟ffmpeg在同一目录,用于查询文件的信息
  ffprobe: /usr/bin/ffprobe
  # [可选 ] 限制 ffmpeg 合并文件使用的线程数，间接限制cpu使用率， 默认2 限制到50%
  threads: 2

#实体类别名
mybatis-plus:
  #映射文件的位置
  mapper-locations: classpath*:top/panll/assist/mapper/**/**.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: top.panll.assist.entity

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

#存储服务器
tqoss:
  ossProtocol: TQFS
  endpoint: 192.168.110.148:20000
  internalEndpoint: 192.168.110.148:20000
  project: test
  bucket: test-video
  accessKey: FcZXiqt256fYOzJv
  accessSecret: LnHozBHjqqAWQXBgy0DTVFUaRfOjN1oJ

swagger-ui:
  enabled: true
knife4j:
  enable: true
# [可选] 日志配置, 一般不需要改
logging:
  file:
    name: logs/wvp.log
    max-history: 30
    max-size: 10MB
    total-size-cap: 300MB
  level:
    root: WARN
    top:
      panll:
        assist: info
